export enum RoleName {
  ADMIN = "ADMIN",
  GERENTE = "GERENTE",
  RECEPCAO = "RECEPCAO",
  MECANICO = "MECANICO",
  ESTOQUE = "ESTOQUE",
  FINANCEIRO = "FINANCEIRO",
  CLIENTE = "CLIENTE",
}

export enum ServiceOrderStatus {
  AGENDADO = "AGENDADO",
  RECEBIDO = "RECEBIDO",
  DIAGNOSTICO = "DIAGNOSTICO",
  ORCAMENTO = "ORCAMENTO",
  AGUARDANDO_APROVACAO = "AGUARDANDO_APROVACAO",
  APROVADO = "APROVADO",
  EM_EXECUCAO = "EM_EXECUCAO",
  AGUARDANDO_PECA = "AGUARDANDO_PECA",
  CONTROLE_QUALIDADE = "CONTROLE_QUALIDADE",
  PRONTO = "PRONTO",
  ENTREGUE = "ENTREGUE",
  ENCERRADO = "ENCERRADO",
}

export enum StockMovementType {
  ENTRADA = "ENTRADA",
  SAIDA = "SAIDA",
  DEVOLUCAO = "DEVOLUCAO",
  AJUSTE = "AJUSTE",
  TRANSFERENCIA = "TRANSFERENCIA",
}

export enum PaymentMethodType {
  PIX = "PIX",
  DINHEIRO = "DINHEIRO",
  DEBITO = "DEBITO",
  CREDITO = "CREDITO",
  BOLETO = "BOLETO",
}

export enum MediaType {
  PHOTO = "PHOTO",
  VIDEO = "VIDEO",
}

export enum MediaStage {
  ENTRADA = "ENTRADA",
  DIAGNOSTICO = "DIAGNOSTICO",
  EXECUCAO = "EXECUCAO",
  FINALIZACAO = "FINALIZACAO",
}

export enum QuoteStatus {
  RASCUNHO = "RASCUNHO",
  ENVIADO = "ENVIADO",
  APROVADO = "APROVADO",
  PARCIAL = "PARCIAL",
  RECUSADO = "RECUSADO",
}

export enum AccountReceivableStatus {
  PENDENTE = "PENDENTE",
  PAGO = "PAGO",
  ATRASADO = "ATRASADO",
}
